### ISSUE TITLE
About building

### ISSUE THREAD

**Issue by NiteSpicy** [Alexander9673/proxy#3]
Im new to here and I don't know about TypeScript, could you make some info about building to wiki?

**Comment by Syn9673** [comment]
![done](https://user-images.githubusercontent.com/59809478/91632702-2689cf80-ea15-11ea-9536-efafe4cb4d93.PNG)
@InjectionZ

**Comment by arshizx** [comment]
What about
```typescript
import Tank from "./Tank";
```
@Alexander9673

**Comment by Syn9673** [comment]
Hm i forgot about the file lol its uploaded now @arshizx

**Comment by arshizx** [comment]
> 
> 
> Hm i forgot about the file lol its uploaded now @arshizx

thx
